# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_mainshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.CharField(max_length=20)),
                ('typename', models.CharField(max_length=100)),
                ('childtypenames', models.CharField(max_length=100)),
                ('typesort', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'axf_foodtypes',
            },
        ),
    ]
