# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('aid', models.IntegerField(primary_key=True, serialize=False)),
                ('aname', models.CharField(max_length=50)),
                ('acontent', models.TextField()),
                ('aauthor', models.CharField(max_length=50)),
                ('atime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reid', models.IntegerField(primary_key=True, serialize=False)),
                ('recontent', models.TextField()),
                ('rearticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Article')),
            ],
        ),
    ]
