# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='aid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
